#!/usr/bin/env python3
# generated by malchun
# Mesh class file

from meshpy.tet import MeshInfo

class Mesh():
    """ Mesh class """
    points = []
    faces = []
    info = {
        "type": None,
        "size": None,
        }

    def __init__(self):
        """ Default constructor """

    def __init__(self, points, faces):
        """ Full constructor """
        self.points = points
        self.faces = faces
        update_info()
    
    def __init__(self, filename):
        """ Constructor from file """
        with open(filename, "r") as fin:
            #TODO
            pass    
    
    def update_info(self):
        """ updates mesh info """
        #TODO
        pass

    def check(self):
        """ Simple check if the mesh is correct... in some meaning """
        #TODO
        pass

    def write_to(self, filename):
        """ Writes mesh in file """
        #TODO
        pass

    def write_points_to_csv(self, filename):
        """ For ParaView """
        with open(filenam, "w") as csvout:
            print("x,y,z", file=csvout)
            for point in self.points:
                print(",".join(point), file=csvout)
